;(function(){
  if (window.__GETINSPIRE_AGG_RUNNING__) return;
  window.__GETINSPIRE_AGG_RUNNING__ = true;

  let zip = null;
  const pages = [];
  let startedAt = Date.now();
  let siteTitle = '';
  let heartbeatId = null;

  function ensureZip(){ if (!zip) zip = new (window.JSZip||function(){ throw new Error('JSZip missing'); })(); }
  function escHtml(s){ return String(s||'').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c])); }
  function slugify(input){ try{ const u = new URL(input); const s = (u.hostname + u.pathname).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,''); return s || 'page'; }catch{ return String(input||'page').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'page'; } }

  chrome.runtime.onMessage.addListener(async (msg) => {
    if (msg?.type === 'GETINSPIRE_AGG_INIT'){
      try { ensureZip(); } catch (e) { console.error(e); return; }
      startedAt = Date.now();
      siteTitle = String(msg?.title || 'GetInspire Site Snapshot');
      try { chrome.runtime.sendMessage({ type:'GETINSPIRE_CRAWL_PROGRESS', done: 0, total: 0, status:'Aggregator ready' }); } catch {}
      try {
        if (heartbeatId) clearInterval(heartbeatId);
        heartbeatId = setInterval(() => { try { chrome.runtime.sendMessage({ type: 'GETINSPIRE_CRAWL_HEARTBEAT' }); } catch {} }, 2000);
      } catch {}
    }
    if (msg?.type === 'GETINSPIRE_AGG_ADD_PAGE'){
      try {
        ensureZip();
        const slug = msg.slug || slugify(msg.pageUrl||('page-'+(pages.length+1)));
        const base = `pages/${slug}/`;

        console.log(`[Aggregator] Adding page: ${slug}`, msg.pageUrl);

        // page index
        zip.file(base + 'index.html', msg.indexHtml || '<!doctype html><title>Empty</title>');
        // assets
        const assets = Array.isArray(msg.assets) ? msg.assets : [];
        console.log(`[Aggregator] Page has ${assets.length} assets`);

        for (const a of assets){
          try {
            const raw = a.arrayBuffer || a.ab || a.data || null;
            if (!raw) continue;
            const blob = raw instanceof Blob ? raw : new Blob([raw], { type: a.mime || 'application/octet-stream' });
            zip.file(base + (a.path || 'assets/asset'), blob);
          } catch (e) { console.error(e); }
        }
        // extras (manifest, mhtml, readme, quick-check, report)
        if (msg.readmeMd) zip.file(base + 'report/README.md', msg.readmeMd);
        if (msg.reportJson) zip.file(base + 'report/fetch-report.json', msg.reportJson);
        if (msg.quickCheckHtml) zip.file(base + 'quick-check.html', msg.quickCheckHtml);
        if (Array.isArray(msg.extras)){
          for (const ex of msg.extras){
            try {
              const p = base + (ex.path || 'extra.bin');
              if (ex.type === 'text') zip.file(p, String(ex.data||''));
              else if (ex.type === 'blob' && ex.data) zip.file(p, ex.data);
              else if (ex.type === 'arrayBuffer' && ex.data) zip.file(p, ex.data);
            } catch (e) { console.error(e); }
          }
        }
        pages.push({ slug, title: msg.title || msg.pageUrl || slug, url: msg.pageUrl || '' });
      } catch (e) { console.error(e); }
    }
    if (msg?.type === 'GETINSPIRE_AGG_FINALIZE'){
      try {
        ensureZip();
        console.log(`[Aggregator] Finalizing ZIP with ${pages.length} pages`);
        const elapsed = Math.max(0, Date.now()-startedAt);
        const list = pages.map(p => `<li><a href="pages/${p.slug}/index.html">${escHtml(p.title)}</a></li>`).join('\n');
        const idx = `<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${escHtml(siteTitle)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <style>
    body { font: 16px system-ui, sans-serif; margin: 20px auto; max-width: 1200px; padding: 0 20px; }
    h1 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }
    .stats { background: #f0f0f0; padding: 10px; border-radius: 5px; margin: 20px 0; }
    ul { list-style: none; padding: 0; }
    li { margin: 10px 0; padding: 10px; background: white; border: 1px solid #ddd; border-radius: 5px; }
    li:hover { background: #f9f9f9; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
    a { color: #007bff; text-decoration: none; font-weight: 500; }
    a:hover { text-decoration: underline; }
    .url { color: #666; font-size: 12px; margin-left: 10px; }
  </style>
</head>
<body>
  <h1>${escHtml(siteTitle)}</h1>
  <div class="stats">
    <strong>📊 Statistics:</strong> ${pages.length} pages captured • Generated in ${Math.round(elapsed/1000)}s
  </div>
  <h2>📄 Captured Pages:</h2>
  <ul>
    ${pages.map(p => `<li><a href="pages/${p.slug}/index.html">${escHtml(p.title)}</a><span class="url">${escHtml(p.url)}</span></li>`).join('\n    ')}
  </ul>
  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 14px;">
    Generated by GetInspire Chrome Extension
  </div>
</body>
</html>`;
        // Always create the main index
        zip.file('index.html', idx);

        // Add a README for clarity
        const readme = `# ${siteTitle}\n\nThis archive contains ${pages.length} pages captured by GetInspire.\n\n## How to use:\n1. Extract this ZIP file\n2. Open index.html in your browser\n3. Navigate through the captured pages\n\nEach page is stored in its own folder under /pages/ with all associated assets.`;
        zip.file('README.md', readme);

        console.log('[Aggregator] Generating ZIP file...');
        // Use DEFLATE compression for site ZIP to reduce size
        const blob = await zip.generateAsync({
          type: 'blob',
          compression: 'DEFLATE',
          compressionOptions: { level: 6 }  // Balanced compression
        });

        console.log(`[Aggregator] ZIP generated: ${(blob.size / 1024 / 1024).toFixed(2)} MB`);

        const URLRef = (window.URL||self.URL);
        const blobUrl = URLRef.createObjectURL(blob);
        const filename = msg.filename || `getinspire-site-${new Date().toISOString().replace(/[:.]/g,'-')}.zip`;
        chrome.runtime.sendMessage({ type:'GETINSPIRE_DOWNLOAD_ZIP', blobUrl, filename });
        setTimeout(()=>{ try { URLRef.revokeObjectURL(blobUrl); } catch{} }, 45000);
        try { if (heartbeatId) { clearInterval(heartbeatId); heartbeatId = null; } } catch {}
      } catch (e) { console.error(e); }
    }
  });
})();
