export const defaults = {
  maxMillis: 90_000,
  maxAssets: 2500,
  maxZipMB: 750,
  concurrency: 8,
  requestTimeoutMs: 20_000,
  scrollIdleMs: 2_000,
  maxScrollIterations: 200,
  redact: true,
  saveWithoutPrompt: false,
  skipVideo: false,
  replaceIframesWithPoster: true,
  stripScripts: false,
  fontFallback: true,
  showOverlay: false,
  denylist: [
    String(/https?:\/\/(www\.)?google\.[^\/]+\/search/i),
    String(/https?:\/\/([^\/]+\.)?(x\.com|twitter\.com)\//i),
    String(/https?:\/\/([^\/]+\.)?(facebook\.com|instagram\.com|tiktok\.com)\//i),
    String(/https?:\/\/([^\/]+\.)?(reddit\.com)\//i),
    String(/https?:\/\/([^\/]+\.)?linkedin\.com\/feed/i),
    String(/https?:\/\/([^\/]+\.)?pinterest\.[^\/]+\//i),
    String(/https?:\/\/([^\/]+\.)?medium\.com\/$/i),
    String(/https?:\/\/news\.google\.com\//i),
    String(/https?:\/\/([^\/]+\.)?quora\.com\//i),
    String(/https?:\/\/([^\/]+\.)?youtube\.com\/feed\//i),
    String(/https?:\/\/([^\/]+\.)?tumblr\.com\/dashboard/i),
  ],
};
